<?php

use App\Enums\InviteStatus;
use App\Filament\Widgets\PendingInvitationsWidget;
use App\Models\Presentation;
use App\Models\PresentationUser;
use App\Models\User;
use Illuminate\Support\Facades\Notification;

use function Pest\Livewire\livewire;

beforeEach(function () {
    Notification::fake();

    $this->owner = User::factory()->create();
    $this->presentation = Presentation::factory()->create(['user_id' => $this->owner->id]);
    $this->user = User::factory()->create();

    $this->invitation = PresentationUser::create([
        'presentation_id' => $this->presentation->id,
        'user_id' => $this->user->id,
        'email' => $this->user->email,
        'invite_status' => InviteStatus::PENDING,
        'invited_at' => now(),
    ]);

    $this->actingAs($this->user);
});

it('renders a pending invitation', function () {
    // The widget's markup is hand-written rather than generated by Filament, so
    // this guards the Blade components it depends on.
    livewire(PendingInvitationsWidget::class)
        ->assertSuccessful()
        ->assertSee($this->presentation->title)
        ->assertSee($this->owner->name)
        ->assertSee('Accept')
        ->assertSee('Reject');
});

it('styles itself with Filament classes rather than bare Tailwind utilities', function () {
    // Filament stopped shipping raw Tailwind utilities in the panel CSS, and
    // this app's Tailwind build never loads inside the panel, so utilities
    // written here would render unstyled with nothing to catch it.
    $html = livewire(PendingInvitationsWidget::class)->html();

    expect($html)
        ->toContain('fi-section')
        ->toContain('fi-btn');

    foreach (['bg-gray-50', 'dark:bg-gray-800', 'rounded-lg', 'justify-between', 'font-medium'] as $utility) {
        expect($html)->not->toContain($utility);
    }
});

it('accepts an invitation', function () {
    livewire(PendingInvitationsWidget::class)
        ->call('acceptInvitation', $this->invitation->id);

    expect($this->invitation->refresh()->invite_status)
        ->toBe(InviteStatus::ACCEPTED);
});

it('rejects an invitation', function () {
    livewire(PendingInvitationsWidget::class)
        ->call('rejectInvitation', $this->invitation->id);

    expect($this->invitation->refresh()->invite_status)
        ->toBe(InviteStatus::REJECTED);
});

it('is hidden when there are no pending invitations', function () {
    $this->invitation->delete();

    expect(PendingInvitationsWidget::canView())->toBeFalse();
});
