<?php

namespace App\Filament\Resources;

use App\Enums\SlideDelimiter;
use App\Filament\Resources\PresentationResource\Pages\CreatePresentation;
use App\Filament\Resources\PresentationResource\Pages\EditPresentation;
use App\Filament\Resources\PresentationResource\Pages\ListPresentations;
use App\Filament\Resources\PresentationResource\RelationManagers\SharedUsersRelationManager;
use App\Jobs\GenerateThumbnail;
use App\Models\Presentation;
use App\Models\User;
use Closure;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ForceDeleteBulkAction;
use Filament\Actions\ReplicateAction;
use Filament\Actions\RestoreBulkAction;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\MarkdownEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Schema;
use Filament\Tables\Columns\SpatieMediaLibraryImageColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ToggleColumn;
use Filament\Tables\Filters\TrashedFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\HtmlString;
use Illuminate\Support\Str;
use Illuminate\Validation\Rules\Unique;

/**
 * @extends resource<Presentation>
 */
class PresentationResource extends Resource
{
    protected static ?string $model = Presentation::class;

    protected static string|\BackedEnum|null $navigationIcon = 'heroicon-o-presentation-chart-bar';

    protected static string|\UnitEnum|null $navigationGroup = 'Main';

    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                Grid::make()
                    ->columnSpanFull()
                    ->columns(3)
                    ->schema([
                        MarkdownEditor::make('content')
                            ->required()
                            ->default(Presentation::DEFAULT_MARKDOWN)
                            ->hint(function (Get $get): HtmlString {
                                // The model casts slide_delimiter to the enum, and v4
                                // hands enum-backed state back as an instance rather
                                // than a scalar, so accept either shape.
                                $delimiter = $get('slide_delimiter');

                                if (! $delimiter instanceof SlideDelimiter) {
                                    $delimiter = SlideDelimiter::tryFrom((string) $delimiter);
                                }

                                return new HtmlString(
                                    '<strong>Tip:</strong> '
                                    .'Slides are separated by '
                                    .$delimiter?->helperText()
                                );
                            })->helperText(new HtmlString(
                                'Want an example? See the site\'s '
                                .'<u><a target="_blank" href="/instructions.md">instructions</a></u>.'
                            ))->columnSpan([
                                'md' => 2,
                            ])->disableToolbarButtons([
                                'attachFiles',
                            ])->saveUploadedFileAttachmentUsing(function () {
                                // Block images from being uploaded.
                                // This prevents drag-and-drop uploads.
                                return null;
                            })->getFileAttachmentUrlUsing(function () {
                                // Required to go along with a null `saveUploadedFileAttachmentUsing`
                                return null;
                            }),
                        Section::make('Details')
                            ->columnSpan(1)
                            ->schema([
                                TextInput::make('title')
                                    ->required()
                                    ->live(debounce: 500)
                                    ->afterStateUpdated(fn ($state, callable $set) => $set('slug', Str::slug($state)))
                                    ->maxLength(255),
                                TextInput::make('slug')
                                    ->required()
                                    ->hintIcon('heroicon-o-information-circle', tooltip: 'The slug is autogenerated from the title, but you can still change it.')
                                    ->unique(
                                        ignoreRecord: true,
                                        modifyRuleUsing: fn (Unique $rule, Get $get) => $rule->where('user_id', $get('user_id')),
                                    )
                                    ->maxLength(255),
                                Select::make('user_id')
                                    ->relationship('user', 'name')
                                    ->hidden(fn () => ! auth()->user()->isAdministrator())
                                    ->searchable()
                                    ->default(auth()->id()),
                                Hidden::make('user_id')
                                    ->default(auth()->id()),
                                Toggle::make('is_published')
                                    ->label('Published')
                                    ->helperText('You can always view your own presentations, but if they aren\'t published, then no one else can.'),
                                Textarea::make('description')
                                    ->helperText(
                                        'A short summary of your presentation. '
                                        .'This will be only be seen when sharing via social media. '
                                        .'Limit is 160 characters.'
                                    )->placeholder('In this talk, we explore...')
                                    ->maxLength(160),

                                Select::make('slide_delimiter')
                                    ->label('Slide Delimiter')
                                    ->required()
                                    ->live()
                                    ->hintIcon('heroicon-o-information-circle',
                                        tooltip: SlideDelimiter::TOOLTIP
                                    )
                                    ->selectablePlaceholder(false)
                                    ->default(SlideDelimiter::DOUBLE_NEW_LINE->value)
                                    ->options(SlideDelimiter::array()),
                                SpatieMediaLibraryFileUpload::make('thumbnail')
                                    ->visibility('public')
                                    ->collection('thumbnail')
                                    ->image()
                                    ->imageEditor()
                                    ->imageResizeMode('cover')
                                    ->imageCropAspectRatio(
                                        // Filament validates uploads against this
                                        // ratio, and Laravel parses it as `%f/%d`,
                                        // so it must be a decimal against 1.
                                        round(Presentation::THUMBNAIL_WIDTH / Presentation::THUMBNAIL_HEIGHT, 4).':1'
                                    )
                                    ->imageResizeTargetWidth((string) Presentation::THUMBNAIL_WIDTH)
                                    ->imageResizeTargetHeight((string) Presentation::THUMBNAIL_HEIGHT)
                                    ->rules([
                                        function () {
                                            return function (string $attribute, $value, Closure $fail) {
                                                if (auth()->user()->can('upload', User::class)) {
                                                    return;
                                                }

                                                $fail(config('app-upload.limit_exceeded_message'));
                                            };
                                        },
                                    ])
                                    ->hintAction(
                                        Action::make('Generate Thumbnail')
                                            ->label('Auto-Generate')
                                            ->disabled(fn (?Presentation $record) => ! $record?->id)
                                            ->requiresConfirmation()
                                            ->size('sm')
                                            ->color('info')
                                            ->modalHeading('Generate a thumbnail of your first slide')
                                            ->modalIcon('heroicon-o-camera')
                                            ->modalIconColor('info')
                                            ->modalDescription(new HtmlString(
                                                'This will overwrite any existing thumbnail that you have '
                                                    .'set for this presentation. Do you wish to continue?'
                                                    .'<br><br><strong>Note:</strong> Your presentation must first be published.'
                                            ))->modalSubmitActionLabel('Generate it')
                                            ->action(function (Presentation $record) {
                                                if (! $record->is_published) {
                                                    Notification::make()
                                                        ->title('You must publish your presentation to generate a thumbnail.')
                                                        ->danger()
                                                        ->send();

                                                    return;
                                                }

                                                Notification::make()
                                                    ->title(
                                                        'Hang tight, your thumbnail is being generated in '
                                                            .'the background. Please refresh your browser in 5-10 '
                                                            .'seconds.'
                                                    )->info()
                                                    ->send();

                                                GenerateThumbnail::dispatch(
                                                    presentation: $record,
                                                    user: auth()->user(),
                                                );
                                            }),
                                    )
                                    ->helperText(new HtmlString(
                                        'Image Size: 1200 x 630. This will be only be seen when sharing via social media. '
                                        .'If omitted, the '
                                        .'<u><a target="_blank" href="/images/simple-slides-og.jpg">default Simple Slides thumbnail</a></u> '
                                        .'will be used.'
                                    )),
                            ]),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('updated_at', 'desc')
            ->columns([
                SpatieMediaLibraryImageColumn::make('thumbnail')
                    ->visibility('public')
                    ->collection('thumbnail'),
                TextColumn::make('title')
                    ->sortable()
                    ->searchable(),
                TextColumn::make('slug')
                    ->sortable()
                    ->toggleable()
                    ->searchable(),
                ToggleColumn::make('is_published')
                    ->label('Published')
                    ->sortable(),
                TextColumn::make('user.name')
                    ->hidden(fn () => ! auth()->user()->isAdministrator())
                    ->sortable(),
                TextColumn::make('created_at')
                    ->date()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->date()
                    ->sortable()
                    ->toggleable(),
                TextColumn::make('deleted_at')
                    ->date()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            // v4 defers filters behind an Apply button by default; these are
            // one-click toggles, so keep them applying immediately.
            ->deferFilters(false)
            ->filters([
                TrashedFilter::make(),
            ])
            ->recordActions([
                ActionGroup::make([
                    Action::make('View')
                        ->url(fn (Presentation $record): string => route('presentations.show', [
                            'user' => $record->user->username,
                            'slug' => $record->slug,
                        ]))
                        ->icon('heroicon-o-arrow-top-right-on-square')
                        ->openUrlInNewTab(),
                    EditAction::make(),
                    ReplicateAction::make()
                        ->beforeReplicaSaved(function (Presentation $replica, Presentation $record): void {
                            $replica->title = 'Copy of '.$record->title;
                            $replica->slug = 'copy-of-'.$record->slug;
                            $replica->is_published = false;
                        })
                        ->successNotificationTitle('Presentation replicated'),
                ]),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                    ForceDeleteBulkAction::make(),
                    RestoreBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            SharedUsersRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => ListPresentations::route('/'),
            'create' => CreatePresentation::route('/create'),
            'edit' => EditPresentation::route('/{record}/edit'),
        ];
    }

    /**
     * Modify the base eloquent table query.
     *
     * @return Builder<Presentation>
     */
    public static function getEloquentQuery(): Builder
    {
        return Presentation::query()
            ->withoutGlobalScopes([
                SoftDeletingScope::class,
            ])
            ->forUser();
    }
}
