<?php

namespace App\Filament\Resources\Presentations\Schemas;

use App\Enums\SlideDelimiter;
use App\Jobs\GenerateThumbnail;
use App\Models\Presentation;
use App\Models\User;
use Closure;
use Filament\Actions\Action;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\MarkdownEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Notifications\Notification;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Schema;
use Illuminate\Support\HtmlString;
use Illuminate\Support\Str;
use Illuminate\Validation\Rules\Unique;

class PresentationForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Grid::make()
                    ->columnSpanFull()
                    ->columns(3)
                    ->schema([
                        MarkdownEditor::make('content')
                            ->required()
                            ->default(Presentation::DEFAULT_MARKDOWN)
                            ->hint(function (Get $get): HtmlString {
                                // The model casts slide_delimiter to the enum, and v4
                                // hands enum-backed state back as an instance rather
                                // than a scalar, so accept either shape.
                                $delimiter = $get('slide_delimiter');

                                if (! $delimiter instanceof SlideDelimiter) {
                                    $delimiter = SlideDelimiter::tryFrom((string) $delimiter);
                                }

                                return new HtmlString(
                                    '<strong>Tip:</strong> '
                                    .'Slides are separated by '
                                    .$delimiter?->helperText()
                                );
                            })->helperText(new HtmlString(
                                'Want an example? See the site\'s '
                                .'<u><a target="_blank" href="/instructions.md">instructions</a></u>.'
                            ))->columnSpan([
                                'md' => 2,
                            ])->disableToolbarButtons([
                                'attachFiles',
                            ])->saveUploadedFileAttachmentUsing(function () {
                                // Block images from being uploaded.
                                // This prevents drag-and-drop uploads.
                                return null;
                            })->getFileAttachmentUrlUsing(function () {
                                // Required to go along with a null `saveUploadedFileAttachmentUsing`
                                return null;
                            }),
                        Section::make('Details')
                            ->columnSpan(1)
                            ->schema([
                                TextInput::make('title')
                                    ->required()
                                    ->live(debounce: 500)
                                    ->afterStateUpdated(fn ($state, callable $set) => $set('slug', Str::slug($state)))
                                    ->maxLength(255),
                                TextInput::make('slug')
                                    ->required()
                                    ->hintIcon('heroicon-o-information-circle', tooltip: 'The slug is autogenerated from the title, but you can still change it.')
                                    ->unique(
                                        ignoreRecord: true,
                                        modifyRuleUsing: fn (Unique $rule, Get $get) => $rule->where('user_id', $get('user_id')),
                                    )
                                    ->maxLength(255),
                                Select::make('user_id')
                                    ->relationship('user', 'name')
                                    ->hidden(fn () => ! auth()->user()->isAdministrator())
                                    ->searchable()
                                    ->default(auth()->id()),
                                Hidden::make('user_id')
                                    ->default(auth()->id()),
                                Toggle::make('is_published')
                                    ->label('Published')
                                    ->helperText('You can always view your own presentations, but if they aren\'t published, then no one else can.'),
                                Textarea::make('description')
                                    ->helperText(
                                        'A short summary of your presentation. '
                                        .'This will be only be seen when sharing via social media. '
                                        .'Limit is 160 characters.'
                                    )->placeholder('In this talk, we explore...')
                                    ->maxLength(160),

                                Select::make('slide_delimiter')
                                    ->label('Slide Delimiter')
                                    ->required()
                                    ->live()
                                    ->hintIcon('heroicon-o-information-circle',
                                        tooltip: SlideDelimiter::TOOLTIP
                                    )
                                    ->selectablePlaceholder(false)
                                    ->default(SlideDelimiter::DOUBLE_NEW_LINE->value)
                                    ->options(SlideDelimiter::array()),
                                SpatieMediaLibraryFileUpload::make('thumbnail')
                                    ->visibility('public')
                                    ->collection('thumbnail')
                                    ->image()
                                    ->imageEditor()
                                    ->imageResizeMode('cover')
                                    ->imageCropAspectRatio(
                                        // Filament validates uploads against this
                                        // ratio, and Laravel parses it as `%f/%d`,
                                        // so it must be a decimal against 1.
                                        round(Presentation::THUMBNAIL_WIDTH / Presentation::THUMBNAIL_HEIGHT, 4).':1'
                                    )
                                    ->imageResizeTargetWidth((string) Presentation::THUMBNAIL_WIDTH)
                                    ->imageResizeTargetHeight((string) Presentation::THUMBNAIL_HEIGHT)
                                    ->rules([
                                        function () {
                                            return function (string $attribute, $value, Closure $fail) {
                                                if (auth()->user()->can('upload', User::class)) {
                                                    return;
                                                }

                                                $fail(config('app-upload.limit_exceeded_message'));
                                            };
                                        },
                                    ])
                                    ->hintAction(
                                        Action::make('Generate Thumbnail')
                                            ->label('Auto-Generate')
                                            ->disabled(fn (?Presentation $record) => ! $record?->id)
                                            ->requiresConfirmation()
                                            ->size('sm')
                                            ->color('info')
                                            ->modalHeading('Generate a thumbnail of your first slide')
                                            ->modalIcon('heroicon-o-camera')
                                            ->modalIconColor('info')
                                            ->modalDescription(new HtmlString(
                                                'This will overwrite any existing thumbnail that you have '
                                                    .'set for this presentation. Do you wish to continue?'
                                                    .'<br><br><strong>Note:</strong> Your presentation must first be published.'
                                            ))->modalSubmitActionLabel('Generate it')
                                            ->action(function (Presentation $record) {
                                                if (! $record->is_published) {
                                                    Notification::make()
                                                        ->title('You must publish your presentation to generate a thumbnail.')
                                                        ->danger()
                                                        ->send();

                                                    return;
                                                }

                                                Notification::make()
                                                    ->title(
                                                        'Hang tight, your thumbnail is being generated in '
                                                            .'the background. Please refresh your browser in 5-10 '
                                                            .'seconds.'
                                                    )->info()
                                                    ->send();

                                                GenerateThumbnail::dispatch(
                                                    presentation: $record,
                                                    user: auth()->user(),
                                                );
                                            }),
                                    )
                                    ->helperText(new HtmlString(
                                        'Image Size: 1200 x 630. This will be only be seen when sharing via social media. '
                                        .'If omitted, the '
                                        .'<u><a target="_blank" href="/images/simple-slides-og.jpg">default Simple Slides thumbnail</a></u> '
                                        .'will be used.'
                                    )),
                            ]),
                    ]),
            ]);
    }
}
